apiVersion: v1
kind: Service
metadata:
  name: deploy-pipeline-app-service
  namespace: default
  labels:
    app: deploy-pipeline-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: deploy-pipeline-app
